In [9]:
import numpy as np

In [10]:
data = np.array([[0,0],[1,0],[0,1],[1,1]])

In [11]:
def make_w(method):
    method_dict = {
        'And':[0,0,0,1],
        'Or':[0,1,1,1],
        'Nor':[1,0,0,0],
        'Nand':[1,1,1,0]
    }
    data = np.array([[0,0],[1,0],[0,1],[1,1]])
    for w1 in np.linspace(0,1,20):
        for w2 in np.linspace(0,1,20):
            for theta in np.linspace(-1,1,20):
                if method in ['Nor', 'Nand']:
                    if np.sum(np.where(data[:,0]*w1 + data[:,1]*w2 > theta,0,1) == method_dict.get(method)) == 4:
                        return -w1, -w2, -theta
                else:
                    if np.sum(np.where(data[:,0]*w1 + data[:,1]*w2 < theta,0,1) == method_dict.get(method)) == 4:
                        return w1, w2, theta

In [12]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [13]:
def loss(y_hat):
    loss_val = np.sum(-((1-y)*np.log(1-y_hat) + y*np.log(y_hat)))
    return loss_val

In [14]:
def gradient(W,b):
    cols = W.shape[1]
    rows = W.shape[0]
    dW = np.zeros_like(W)
    db = np.zeros(1)
    h = 1e-5
    for col in range(cols):
        for row in range(rows):
            y_hat = sigmoid(np.dot(X,W)+b)
            fx = loss(y_hat)
            tmp = W[row,col]
            W[row,col] += h
            y_hat = sigmoid(np.dot(X,W)+b)
            fxh = loss(y_hat)
            dW[row,col] = (fxh-fx)/h
            W[row,col] = tmp
    for idx in range(b.size):
        y_hat = sigmoid(np.dot(X,W)+b)
        fx = loss(y_hat)
        tmp = b[idx]
        b[idx] += h
        y_hat = sigmoid(np.dot(X,W)+b)
        fxh = loss(y_hat)
        db[idx] = (fxh-fx)/h
        b[idx] = tmp
    return dW, db

In [42]:
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([1,0,0,0]).reshape(4,1)

In [43]:
W = np.random.randn(2,1)
b = np.zeros(1)

In [44]:
lr = 1e-3
for _ in range(10000):
    W -= gradient(W,b)[0]*lr
    b -= gradient(W,b)[1]*lr

In [45]:
np.where(sigmoid(np.dot(X,W) + b) > 0.5,1,0)

array([[1],
       [0],
       [0],
       [0]])

In [390]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

In [48]:
X.shape

(4, 2)

In [49]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

y1 = np.array([0,0,0,1]).reshape(4,1)
y2 = np.array([1,1,1,0]).reshape(4,1)
y3 = np.array([0,1,1,1]).reshape(4,1)
y4 = np.array([1,0,0,0]).reshape(4,1)
y5 = np.array([0,1,1,0]).reshape(4,1) 
y6 = np.array([1,0,0,1]).reshape(4,1)

In [52]:
W = np.random.randn(X.shape[1],y1.shape[1])
b = np.zeros(y1.shape[1])

In [53]:
y_hat = np.dot(X,W) + b
y_hat = sigmoid(y_hat)

In [55]:
def loss(y_hat, y):
    return -np.sum((1-y)*np.log(1-y_hat) + y*np.log(y_hat))

In [56]:
loss(y_hat, y)

3.9388257796066153

In [59]:
W[0,0], W[1,0]

(0.6434523122008795, 0.34091516955861784)

In [73]:
# (fxh - fx)/h --> gradient
print(W)
h = 1e-5
y_hat = np.dot(X,W) + b
y_hat = sigmoid(y_hat)
fx = loss(y_hat, y1)

tmp = W[0,0]
W[0,0] += h
y_hat = np.dot(X,W) + b
y_hat = sigmoid(y_hat)
fxh = loss(y_hat, y1)
dW1 = (fxh - fx)/h
W[0,0] = tmp

tmp = W[1,0]
W[1,0] += h
y_hat = np.dot(X,W) + b
y_hat = sigmoid(y_hat)
fxh = loss(y_hat, y1)
dW2 = (fxh - fx)/h
dW = np.array([dW1, dW2]).reshape(2,1)
print(dW)

[[0.64348231]
 [0.34097517]]
[[0.38353412]
 [0.31242137]]


In [74]:
loss(y_hat, y1)

2.9544916718299943

In [75]:
y_hat = np.dot(X, W-1e-3*dW) + b
y_hat = sigmoid(y_hat)
loss(y_hat, y1)

2.954247042084172

In [ ]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [108]:
def predict(x,W,b):
    return sigmoid(np.dot(x,W) + b)    

In [109]:
def loss(y_hat, y):
    return -np.sum((1-y)*np.log(1-y_hat) + y*np.log(y_hat))

In [137]:
# X * W + b
def gradient(x, y, W, b):
    h = 1e-5
    dW = np.zeros_like(W)
    db = np.zeros_like(b)
    cols = range(W.shape[1])
    rows = range(W.shape[0])
    for col in cols:
        for row in rows:
            y_hat = predict(x,W,b)
            fx = loss(y_hat,y)
            tmp = W[row,col]
            W[row,col] += h
            y_hat = predict(x,W,b)
            fxh = loss(y_hat, y)
            dW[row,col] = (fxh - fx)/h
            W[row,col] = tmp
    for i in range(db.size):
        y_hat = predict(x,W,b)
        fx = loss(y_hat,y)
        tmp = b[i]
        b[i] += h
        y_hat = predict(x,W,b)
        fxh = loss(y_hat, y)
        db[i] = (fxh - fx)/h
        b[i] = tmp
    return dW, db

In [138]:
W = np.random.randn(X.shape[1], y1.shape[1])
b = np.zeros(y.shape[1])

In [173]:
def descent_gradient(x,y,lr = 1e-3, epochs = 30000):
    W = np.random.randn(x.shape[1], y.shape[1])
    b = np.zeros(y.shape[1])
    for i in range(epochs):
        W = W - gradient(x,y,W,b)[0] * lr
        b = b - gradient(x,y,W,b)[1] * lr
        y_hat = predict(x,W,b)
        #if i % 100 == 0:
        #    print(f'loss ===> {loss(y_hat, y)}')
    print(y)
    print(np.where(predict(x,W,b)>0.5,1,0))

In [175]:
descent_gradient(X,y6)

[[1]
 [0]
 [0]
 [1]]
[[0]
 [1]
 [0]
 [1]]


In [104]:
gradient(X,y1)

(array([[-0.0803472 ],
        [-0.08345837]]),
 array([0.11883273]))

In [181]:
class Perceptron:
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.W = np.random.randn(x.shape[1], y.shape[1])
        self.b = np.zeros(y.shape[1])
    
    def sigmoid(x):
        return 1/(1+np.exp(-x))
    
    def predict(x,W,b):
        return sigmoid(np.dot(x,W) + b)
    
    def loss(y_hat, y):
        return -np.sum((1-y)*np.log(1-y_hat) + y*np.log(y_hat))
    
    def gradient(x, y, W, b):
        h = 1e-5
        dW = np.zeros_like(W)
        db = np.zeros_like(b)
        cols = range(W.shape[1])
        rows = range(W.shape[0])
        for col in cols:
            for row in rows:
                y_hat = predict(x,W,b)
                fx = loss(y_hat,y)
                tmp = W[row,col]
                W[row,col] += h
                y_hat = predict(x,W,b)
                fxh = loss(y_hat, y)
                dW[row,col] = (fxh - fx)/h
                W[row,col] = tmp
        for i in range(db.size):
            y_hat = predict(x,W,b)
            fx = loss(y_hat,y)
            tmp = b[i]
            b[i] += h
            y_hat = predict(x,W,b)
            fxh = loss(y_hat, y)
            db[i] = (fxh - fx)/h
            b[i] = tmp
        return dW, db
    
    def descent_gradient(x,y,lr = 1e-3, epochs = 10000):
        W = np.random.randn(x.shape[1], y.shape[1])
        b = np.zeros(y.shape[1])
        for i in range(epochs):
            W = W - gradient(x,y,W,b)[0] * lr
            b = b - gradient(x,y,W,b)[1] * lr
            y_hat = predict(x,W,b)
            #if i % 100 == 0:
            #    print(f'loss ===> {loss(y_hat, y)}')
        print(y)
        print(np.where(predict(x,W,b)>0.5,1,0))

In [335]:
y_train.shape

(426,)

In [381]:
class Perceptron:
    def __init__(self,x,y):
        self.x = x
        if y.ndim == 1:
            y = y.reshape(-1,1)
        self.y = y
        self.W = np.random.randn(x.shape[1],y.shape[1])
        self.b = np.zeros(y.shape[1])
    
    def predict_proba(self):
        x = (self.x-self.x.min(0))/self.x.max(0)
        self.y_hat = np.dot(x,self.W) + self.b
        self.y_hat = sigmoid(self.y_hat)
        return self.y_hat
    
    def loss(self):
        result = self.predict_proba()
        return -np.sum((1-self.y)*np.log(1-result)+self.y*np.log(result))
    
    def gradient(self):
        h = 1e-5
        self.dW = np.zeros_like(self.W)
        self.db = np.zeros_like(self.b)
        cols = range(self.W.shape[1])
        rows = range(self.W.shape[0])
        for col in cols:
            for row in rows:
                fx = self.loss()
                tmp = self.W[row,col]
                self.W[row,col] += h
                fxh = self.loss()
                self.dW[row,col] = (fxh-fx)/h
                self.W[row,col] = tmp
        for i in range(self.b.size):
            fx = self.loss()
            tmp = self.b[i]
            self.b[i] += h
            fxh = self.loss()
            self.db[i] = (fxh-fx)/h
            self.b[i] = tmp
        return self.dW, self.db
    
    def desecnt_gradient(self):
        lr = 1e-2
        dW, db = self.gradient()
        self.W -= dW*lr
        self.b -= db*lr
        
    def fit(self,epochs=20000):
        for epoch in range(epochs):
            self.desecnt_gradient()
            # if epoch & 2000 == 0:
            #    print(self.loss())
                
    def predict(self,x):
        x = (x-x.min(0))/x.max(0)
        return np.where(sigmoid(np.dot(x,self.W)+self.b) > 0.5,1,0)
    
    def score(self,x,y):
        if y.ndim == 1:
            y = y.reshape(-1,1)
        return np.sum(self.predict(x) == y)/x.shape[0]

In [320]:
and_ = Perceptron(X,y1)

In [267]:
and_.predict(X)

array([[0],
       [0],
       [0],
       [1]])

In [303]:
nand_ = Perceptron(X,y2)

In [306]:
nand_.predict(X)

array([[1],
       [1],
       [1],
       [0]])

In [277]:
or_ = Perceptron(X,y3)

In [279]:
or_.predict(X)

array([[0],
       [1],
       [1],
       [1]])

In [283]:
nor_ = Perceptron(X,y4)

In [285]:
nor_.predict(X)

array([[1],
       [0],
       [0],
       [0]])

In [287]:
xor_ = Perceptron(X,y5)

In [301]:
xor_.predict(X)

array([[1],
       [1],
       [1],
       [0]])

In [297]:
xnor_ = Perceptron(X,y6)

In [298]:
xnor_.predict(X)

array([[0],
       [0],
       [1],
       [1]])

In [367]:
from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [375]:
X = load_breast_cancer()['data']
y = load_breast_cancer()['target']

In [376]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [377]:
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)
tree_model.score(X_test, y_test)

0.9230769230769231

In [382]:
our_model = Perceptron(X_train, y_train)

In [383]:
our_model.fit()

In [384]:
our_model.score(X_test,y_test)

0.8461538461538461

In [455]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

y1 = np.array([0,0,0,1]).reshape(4,1)
y2 = np.array([1,1,1,0]).reshape(4,1)
y3 = np.array([0,1,1,1]).reshape(4,1)
y4 = np.array([1,0,0,0]).reshape(4,1)
y5 = np.array([0,1,1,0]).reshape(4,1) 
y6 = np.array([1,0,0,1]).reshape(4,1)

In [508]:
class MultiLayer:
    def __init__(self,x,y):
        self.Activation = {
            'sigmoid' : sigmoid
        }
        self.x = x
        if y.ndim ==1:
            y = y.reshape(-1,1)
        self.y = y
        self.W1 = np.random.randn(2,2)
        self.b1 = np.zeros(2)
        self.W2 = np.random.randn(2,1)
        self.b2 = np.zeros(1)
    
    def predict_proba(self):
        x = (self.x - self.x.min(0)) / self.x.max(0)
        self.y_hat = np.dot(x, self.W1) + self.b1
        self.y_hat = self.Activation['sigmoid'](self.y_hat)
        self.y_hat = np.dot(self.y_hat,self.W2) + self.b2
        self.y_hat = self.Activation['sigmoid'](self.y_hat)
        return self.y_hat
    
    def loss(self):
        result = self.predict_proba()
        return -np.sum((1-self.y)*np.log(1-result) + self.y*np.log(result))
    
    def gradient(self):
        h = 1e-5
        self.dW1 = np.zeros_like(self.W1)
        self.dW2 = np.zeros_like(self.W2)
        self.db1 = np.zeros_like(self.b1)
        self.db2 = np.zeros_like(self.b2)
        
        for row in range(self.W1.shape[0]):
            for col in range(self.W1.shape[1]):
                fx = self.loss()
                tmp = self.W1[row,col]
                self.W1[row,col] += h
                fxh = self.loss()
                self.dW1[row,col] = (fxh-fx)/h
                self.W1[row,col] = tmp
                
        for row in range(self.W2.shape[0]):
            for col in range(self.W2.shape[1]):
                fx = self.loss()
                tmp = self.W2[row,col]
                self.W2[row,col] += h
                fxh = self.loss()
                self.dW2[row,col] = (fxh-fx)/h
                self.W2[row,col] = tmp
        
        for i in range(self.b1.size):
            fx = self.loss()
            tmp = self.b1[i]
            self.b1[i] += h
            fxh = self.loss()
            self.db1[i] = (fxh-fx)/h
            self.b1[i] = tmp
        
        for i in range(self.b2.size):
            fx = self.loss()
            tmp = self.b2[i]
            self.b2[i] += h
            fxh = self.loss()
            self.db2[i] = (fxh-fx)/h
            self.b2[i] = tmp
        
        return self.dW1, self.dW2, self.db1, self.db2
                
    
    def descent_gradient(self):
        dW1, dW2, db1, db2 = self.gradient()
        self.W1 -= dW1 * 1e-5
        self.W2 -= dW2 * 1e-5
        self.b1 -= db1 * 1e-5
        self.b2 -= db2 * 1e-5
        
    def fit(self, epochs=100000):
        self.history = []
        for _ in range(epochs):
            self.descent_gradient()
            self.history.append(self.descent_gradient())
    
    def predict(self, x):
        x = (x - x.min(0)) / x.max(0)
        result = np.dot(x, self.W1) + self.b1
        result = self.Activation['sigmoid'](result)
        result = np.dot(result,self.W2) + self.b2
        result = self.Activation['sigmoid'](result)
        return np.where(result > 0.5,1,0)
    
    def score(self, x, y):
        return np.sum(self.predict(x) == y)/x.shape[0]

In [509]:
model = MultiLayer(X, y5)

In [516]:
model.fit()

In [517]:
model.predict(X)

array([[1],
       [0],
       [1],
       [0]])

In [465]:
import tensorflow as tf

In [470]:
from tensorflow.keras import Sequential

In [471]:
from tensorflow.keras.layers import Dense

In [495]:
model_tf = Sequential()

In [496]:
model_tf.add(Dense(10,activation='sigmoid',input_shape=(100,)))

In [497]:
model_tf.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
Total params: 1010 (3.95 KB)
Trainable params: 1010 (3.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [499]:
model_tf.add(Dense(250,activation='relu'))

In [501]:
model_tf.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
 dense_2 (Dense)             (None, 250)               2750      
                                                                 
Total params: 3760 (14.69 KB)
Trainable params: 3760 (14.69 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [515]:
model_tf.layers

In [521]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [522]:
to_categorical(y_train).shape

(60000, 10)

In [523]:
X_train = X_train.reshape(-1,28*28)

In [524]:
X_train.shape

(60000, 784)

In [531]:
y_train = to_categorical(y_train)

In [539]:
model = Sequential()
model.add(Dense(256,activation='sigmoid',input_shape=(784,)))
model.add(Dense(100,activation='sigmoid'))
model.add(Dense(10,activation='softmax'))

In [540]:
opt = 'adam'
loss = 'categorical_crossentropy'
metrics = ['accuracy']
model.compile(loss = loss, optimizer = opt, metrics = metrics)

In [541]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
1206/1875 [==================>...........] - ETA: 1s - loss: 0.5406 - accuracy: 0.8605

KeyboardInterrupt: 

In [553]:
def linear(x):
    return x

def relu(x):
    return np.where(x > 0, x, 0)

In [573]:
class SequentialModel:
    def __init__(self,x,y,output_shape, activation='linear'):
        self.activation_dic = {
            'linear' : linear,
            'sigmoid' : sigmoid,
            'relu' : relu
        }
        self.x = x
        self.y = y
        self.activation = [activation]
        # output_shape = y.shape[1]
        self.W = [[np.random.randn(self.x.shape[1], output_shape), 
                  np.zeros(output_shape)]]
    
    def add(self,output,activation='linear'):
        self.input = self.W[-1][0].shape[1]
        self.W.append([np.random.randn(self.input,output),np.zeros(output)])
        self.activation.append(activation)
        
    def predict(self, x):
        self.y_hat = x.copy()
        for i in range(len(self.W)):
            self.y_hat = np.dot(self.y_hat, self.W[i][0]) + self.W[i][1]
            self.y_hat = self.activation_dic[self.activation[i]](self.y_hat)
        return self.y_hat
    
    def compile(self, loss):
        
        pass
            

In [569]:
model = SequentialModel(np.random.randn(100,20), np.random.randn(100,5),50)

In [570]:
model.add(300,'sigmoid')
model.add(150,'relu')
model.add(5,'relu')

In [571]:
model.predict(np.random.randn(10,20))

array([[  0.        ,   0.        ,   0.        ,   0.        ,
         28.4391368 ],
       [  0.        ,   0.        ,   0.        ,  57.68332959,
        101.60803912],
       [  0.        ,   0.        ,   5.08173566,   0.        ,
          0.        ],
       [  0.        ,   0.        ,  13.42301642,   0.        ,
        170.40175709],
       [  0.        ,   0.        ,   0.        ,  34.98735888,
        126.38626947],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        125.08792415],
       [  0.        ,   0.        ,   3.69725224,  43.35572314,
        166.67577997],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        102.38134595],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        161.96346663],
       [  0.        ,   0.        ,  15.68799133,   0.        ,
        123.02515457]])

In [574]:
model.compile()

AttributeError: 'SequentialModel' object has no attribute 'compile'

In [556]:
model.add(256,activation='sigmoid')

In [558]:
model.W, model.activation

([[array([[ 1.96117089,  0.69807651, -0.83225076, ..., -1.85027514,
            0.65537162,  0.69051308],
          [-1.72899532,  0.71629164, -0.25458445, ...,  0.45514864,
            0.54172202, -0.14524139],
          [-0.5210521 ,  0.1077967 , -0.97102892, ...,  0.00466994,
           -0.6381946 , -0.27971172],
          ...,
          [ 0.76139387,  0.6298401 ,  0.09611707, ...,  0.97273082,
            2.63429522,  0.80512648],
          [-2.1844373 , -0.39863187,  0.18327245, ...,  1.25600288,
           -0.56856501, -0.99857557],
          [-1.17116897, -1.37121831,  0.1911763 , ...,  0.49262461,
           -1.45590873, -0.10380217]]),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0

In [577]:
import torch