In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
load_iris()['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
X = load_iris()['data']
y = load_iris()['target']
species = np.where(y == 0, 'setosa', np.where(y == 1, 'versicolor', 'virginica'))
data = pd.DataFrame(X, columns = load_iris()['feature_names'])
data['species'] = species

In [6]:
# 붓꽃 종류입니다 (sepal :  꽃받침의 길이/너비, petal : 꽃잎의 길이/너비)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [9]:
## 1. 데이터 처리
# 데이터의 eda(exploring data analysis)
# 데이터 전처리 (missing, none)
# 데이터를 tidy 데이터로 만드는 작업
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [12]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [17]:
# 데이터 전처리에 관한 내용을 모아둔 모듈 (model_selection)
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()

In [20]:
le.fit(y)

LabelEncoder()

In [21]:
le.transform(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
# 현 상태로 하면 overfitting이 되어서 나누는게 좋은데 위 데이터를 8:2로 나누면 20%가 전부 '2'만 남기 때문에 섞어서 해줘야한다.
random_idx = np.random.choice(np.arange(150),150,replace=False)
idx = int(len(random_idx) * 0.8)
tr_idx = random_idx[:idx]
te_idx = random_idx[idx:]

In [31]:
X_train = X.iloc[tr_idx,:]
y_train = y[tr_idx]
X_test = X.iloc[te_idx,:]
y_test = y[te_idx]

In [36]:
## 2. 알고리즘 선택
from sklearn.tree import DecisionTreeClassifier

In [38]:
# 2 - 1. 모델 학습
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [41]:
# 몇 % 맞췄는지 확인 (현재는 3개 틀림)
np.sum(clf.predict(X_test) == y_test)/y_test.size

0.9

In [43]:
# 검증
clf.score(X_test,y_test)

0.9

In [44]:
# 이거는 뭔지 다시 설명을 듣기
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [52]:
clf = DecisionTreeClassifier(criterion="gini",max_depth = 10)

In [53]:
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.8666666666666667

In [47]:
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [49]:
clf.get_depth()

7

In [55]:
X_train.shape
X_train.iloc[1,:].shape

(4,)

In [58]:
# clf.predict(만든모양)
clf.predict(X_train.iloc[[1],:])

array(['setosa'], dtype=object)

In [61]:
clf.predict(np.array([5,5,1,2]).reshape(1,4))

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['virginica'], dtype=object)

In [62]:
# 1
# 2 모델
from sklearn.cluster import KMeans

In [70]:
km = KMeans(n_clusters=3)

In [77]:
km.fit(X)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [83]:
result1 = km.labels_

In [84]:
km.cluster_centers_
# 순서대로 0,1,2번일때의 중앙값

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [85]:
km.fit_transform(X)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


array([[0.14135063, 3.41925061, 5.0595416 ],
       [0.44763825, 3.39857426, 5.11494335],
       [0.4171091 , 3.56935666, 5.27935534],
       [0.52533799, 3.42240962, 5.15358977],
       [0.18862662, 3.46726403, 5.10433388],
       [0.67703767, 3.14673162, 4.68148797],
       [0.4151867 , 3.51650264, 5.21147652],
       [0.06618157, 3.33654987, 5.00252706],
       [0.80745278, 3.57233779, 5.32798107],
       [0.37627118, 3.3583767 , 5.06790865],
       [0.4824728 , 3.32449131, 4.89806763],
       [0.25373214, 3.31126872, 4.9966845 ],
       [0.50077939, 3.46661272, 5.19103612],
       [0.91322505, 3.90578362, 5.65173594],
       [1.01409073, 3.646649  , 5.10804455],
       [1.20481534, 3.49427881, 4.88564095],
       [0.6542018 , 3.495248  , 5.03090587],
       [0.1441527 , 3.38444981, 5.02342022],
       [0.82436642, 3.11245944, 4.61792995],
       [0.38933276, 3.37738931, 4.97213426],
       [0.46344363, 3.07471224, 4.6955761 ],
       [0.3286031 , 3.31506588, 4.9236821 ],
       [0.

In [87]:
km.predict(X) == result1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [88]:
from sklearn.model_selection import train_test_split

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:
clf = LogisticRegression()

In [94]:
clf.fit(X_train,y_train)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [95]:
clf.score(X_test,y_test)

0.9333333333333333

In [102]:
clf.predict(X.iloc[[75],:])

array(['versicolor'], dtype=object)

In [106]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [112]:
from sklearn.svm import SVC

In [113]:
clf = SVC()

In [116]:
clf.get_params()
#kernel은 정규분포를 이용하는거

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [115]:
clf = SVC(kernel = 'linear')

In [117]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [118]:
clf.score(X_test,y_test)

0.9666666666666667

In [119]:
clf = SVC()

In [122]:
clf.fit(X_train.iloc[:,:2],y_train)

SVC()

In [123]:
# 변수를 두개가지고만 해서 score가 떨어짐
clf.score(X_test.iloc[:,:2],y_test)

0.8333333333333334

In [124]:
from sklearn.decomposition import PCA

In [125]:
pca = PCA(n_components=2)

In [126]:
pca.fit(X_train)

PCA(n_components=2)

In [127]:
X_pca = pca.transform(X_train)

In [129]:
X_pca.shape

(120, 2)

In [131]:
clf = SVC()
clf.fit(X_pca,y_train)

SVC()

In [132]:
X_pca_test = pca.transform(X_test)

In [135]:
clf.score(X_pca_test,y_test)

0.9333333333333333

In [138]:
group = KMeans(4).fit(X).labels_

C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [140]:
X['gr'] = group

In [142]:
X["sepal length (cm)"]/X["sepal width (cm)"]

0      1.457143
1      1.633333
2      1.468750
3      1.483871
4      1.388889
         ...   
145    2.233333
146    2.520000
147    2.166667
148    1.823529
149    1.966667
Length: 150, dtype: float64