In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [3]:
load_iris()['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
X = load_iris()['data']
y = load_iris()['target']
species = np.where(y == 0, 'setosa', np.where(y==1,'versicolor','virginica'))
data = pd.DataFrame(X, columns=load_iris()['feature_names'])
data['species'] = species

In [5]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [7]:
## 1. 데이터 처리
## 데이터의 eda(exporering data analysis)
## 데이터 전처리 (missing, none )
## 데이터를 tidy데이터로 만드는 작업
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
le.fit(y)

LabelEncoder()

In [15]:
le.transform(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
random_idx = np.random.choice(np.arange(150),150,replace=False)
idx = int(len(random_idx)*0.8)
tr_idx = random_idx[:idx]
te_idx = random_idx[idx:]

In [23]:
X_train = X.iloc[tr_idx,:]
y_train = y[tr_idx]
X_test = X.iloc[te_idx,:]
y_test = y[te_idx]

In [27]:
##2 알고리즘 선택
from sklearn.tree import DecisionTreeClassifier

In [29]:
##2-1 모델학습
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [32]:
np.sum(clf.predict(X_test) == y_test)/y_test.size

0.9333333333333333

In [34]:
clf.score(X_test,y_test)

0.9333333333333333

In [35]:
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [43]:
clf = DecisionTreeClassifier(criterion="gini",max_depth=7)

In [44]:
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9

In [40]:
clf.get_depth()

4

In [45]:
X_train.shape

(120, 4)

In [50]:
X_train.iloc[[1],:].shape

(1, 4)

In [51]:
#clf.predict(만든모양)
clf.predict(X_train.iloc[[1],:])

array(['versicolor'], dtype=object)

In [53]:
clf.predict(np.array([5,5,1,2]).reshape(1,4))

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['setosa'], dtype=object)

In [54]:
# 1  
# 2 모델
from sklearn.cluster import KMeans

In [58]:
km = KMeans(3)

In [59]:
km.fit(X)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [60]:
dir(km)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_algorithm',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_mkl_vcomp',
 '_check_n_features',
 '_check_params_vs_input',
 '_check_test_data',
 '_estimator_type',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_init_centroids',
 '_more_tags',
 '_n_features_out',
 '_n_init',
 '_n_threads',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_tol',
 '_transform',
 '_v

In [62]:
result1 = km.labels_

In [65]:
km.cluster_centers_

array([[6.85      , 3.07368421, 5.74210526, 2.07105263],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

In [68]:
y = km.predict(X)

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
clf = LogisticRegression()

In [74]:
clf.fit(X_train,y_train)

LogisticRegression()

In [75]:
clf.score(X_test,y_test)

1.0

In [81]:
clf.predict(X.iloc[[75],:])

array([2])

In [79]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [84]:
X_train.shape

(120, 4)

In [86]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [88]:
from sklearn.svm import SVC

In [95]:
clf = SVC(kernel='rbf')

In [96]:
clf.fit(X_train, y_train)

SVC()

In [97]:
clf.score(X_test,y_test)

0.9666666666666667

In [98]:
clf = SVC()

In [100]:
clf.fit(X_train.iloc[:,:2],y_train)

SVC()

In [101]:
X_train.iloc[:,:2].shape

(120, 2)

In [103]:
clf.score(X_test.iloc[:,:2],y_test)

0.7666666666666667

In [105]:
from sklearn.decomposition import PCA

In [106]:
pca = PCA(n_components=2)

In [107]:
pca.fit(X_train)

PCA(n_components=2)

In [108]:
X_pca = pca.transform(X_train)

In [109]:
X_pca.shape

(120, 2)

In [110]:
clf = SVC()
clf.fit(X_pca,y_train)

SVC()

In [111]:
X_pca_test = pca.transform(X_test)

In [113]:
clf.score(X_pca_test,y_test)

0.9666666666666667

In [117]:
from sklearn.cluster import KMeans
group = KMeans(4).fit(X).labels_

C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [119]:
X['gr'] = group

In [121]:
X["sepal length (cm)"]/X["sepal width (cm)"]

0      1.457143
1      1.633333
2      1.468750
3      1.483871
4      1.388889
         ...   
145    2.233333
146    2.520000
147    2.166667
148    1.823529
149    1.966667
Length: 150, dtype: float64

In [123]:
X = np.random.randint(1,100,7)

In [125]:
(X-min(X))/(max(X) - min(X))

array([1.  , 0.28, 0.44, 0.04, 0.24, 0.12, 0.  ])

In [126]:
(X-np.mean(X))/np.std(X)

array([ 2.19900149, -0.07209841,  0.43259046, -0.82913171, -0.19827063,
       -0.57678728, -0.95530392])

In [128]:
from sklearn.preprocessing import MinMaxScaler

In [130]:
mmScaler = MinMaxScaler()
mmScaler.fit(X.reshape(-1,1))
mmScaler.transform(X.reshape(-1,1))

array([[1.  ],
       [0.28],
       [0.44],
       [0.04],
       [0.24],
       [0.12],
       [0.  ]])

In [131]:
(X-min(X))/(max(X) - min(X))

array([1.  , 0.28, 0.44, 0.04, 0.24, 0.12, 0.  ])

In [132]:
from sklearn.preprocessing import StandardScaler

In [133]:
StandardScaler().fit_transform(X.reshape(-1,1))

array([[ 2.19900149],
       [-0.07209841],
       [ 0.43259046],
       [-0.82913171],
       [-0.19827063],
       [-0.57678728],
       [-0.95530392]])

In [134]:
(X-np.mean(X))/np.std(X)

array([ 2.19900149, -0.07209841,  0.43259046, -0.82913171, -0.19827063,
       -0.57678728, -0.95530392])

In [138]:
# (X-median)/(Q3-Q1)
(X-np.median(X))/(np.percentile(X,75) - np.percentile(X,25))

array([ 2.71428571,  0.14285714,  0.71428571, -0.71428571,  0.        ,
       -0.42857143, -0.85714286])

In [139]:
from sklearn.preprocessing import RobustScaler

In [141]:
rbScaler = RobustScaler()
rbScaler.fit(X.reshape(-1,1))
rbScaler.transform(X.reshape(-1,1))

array([[ 2.71428571],
       [ 0.14285714],
       [ 0.71428571],
       [-0.71428571],
       [ 0.        ],
       [-0.42857143],
       [-0.85714286]])