In [6]:
## 객체 지향, 함수형 언어
## 모든 것이 다 객체
10 + 10

20

In [7]:
a = 10
b = 10
c = a+b
print(c)

20


In [8]:
dir(10)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [9]:
a = 10
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [11]:
def name(x):
    return 10 + x
obj = 4
name(obj)

14

In [12]:
from datetime import datetime

In [19]:
datetime.now().strftime("%Y%m").replace('2','')

'0309'

In [29]:
s = 0
for i in range(1,11):
    s = s + i
print(s)

55


In [30]:
sum([i for i in range(1,11)])

55

In [31]:
sum(range(1,11))

55

In [36]:
{'key':20,'key':30}

{'key': 30}

In [43]:
if True or abc:
    print("실행")

실행


In [45]:
type([])

list

In [46]:
!pip install numpy

                                              0.0/15.5 MB ? eta -:--:--
     -                                        0.5/15.5 MB 9.8 MB/s eta 0:00:02
     --                                       1.0/15.5 MB 12.1 MB/s eta 0:00:02
     ---                                      1.2/15.5 MB 9.7 MB/s eta 0:00:02
     ---                                      1.3/15.5 MB 7.0 MB/s eta 0:00:03
     ---                                      1.4/15.5 MB 6.4 MB/s eta 0:00:03
     ---                                      1.5/15.5 MB 5.7 MB/s eta 0:00:03
     ----                                     1.7/15.5 MB 5.3 MB/s eta 0:00:03
     ----                                     1.8/15.5 MB 5.0 MB/s eta 0:00:03
     -----                                    2.0/15.5 MB 4.9 MB/s eta 0:00:03
     -----                                    2.2/15.5 MB 4.9 MB/s eta 0:00:03
     ------                                   2.5/15.5 MB 4.9 MB/s eta 0:00:03
     -------                                  2.7/15.5 MB 


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np

In [49]:
a= [1,2,3,4]
b= []
for i in a:
    b.append(i+5)
b

[6, 7, 8, 9]

In [50]:
list(map(lambda x: x+5, a))

[6, 7, 8, 9]

In [51]:
[ i + 5 for i in a]

[6, 7, 8, 9]

In [52]:
def add_5(x):
    return x+5
list(map(add_5,a))

[6, 7, 8, 9]

In [54]:
c = [ ]
for i in range(len(a)):
    c.append(a[i] - b[i])
c

[-5, -5, -5, -5]

In [55]:
c = [ ]
for i,j in zip(a,b):
    c.append(i-j)
c

[-5, -5, -5, -5]

In [ ]:
# [1,2,3,4] = vector (collection)
# 5 = scala
# [5] = vector

In [58]:
X = [1,2,3,4]
X_S = sum(X)
X_M = X_S/len(X)

X_SS = 0
for i in range(len(X)):
    X_SS += (X[i] - X_M)**2 

X_var = X_SS / len(X)
X_var

1.25

In [60]:
X = np.array(X)
np.sum(np.square(X - np.mean(X)))/X.size


1.25

In [61]:
import numpy as np

In [64]:
type(np.array)

builtin_function_or_method

In [70]:
l = [1,2,3,4]
arr = np.array(l)
arr.shape

(4,)

In [77]:
arr.reshape(4,1,1) # axis == 축

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [75]:
l

[1, 2, 3, 4]

In [83]:
np.random.seed(100)
x = np.random.randint(50,100,size=(4,3)) #4는 데이터 개수 , 3은 변수 개수

In [90]:
print(x)
print(x.shape)
print(x.ndim) #차원
print(x.size) #데이터개수
print(x.T) #뒤집기 4,3 -> 3,4 로 #대각선으로 뒤집는거
print(x.transpose())
print(x.reshape(3,4)) #한줄로 쫙 피고 4개씩 끊음

[[58 74 53]
 [89 73 65]
 [98 60 80]
 [84 52 84]]
(4, 3)
2
12
[[58 89 98 84]
 [74 73 60 52]
 [53 65 80 84]]
[[58 89 98 84]
 [74 73 60 52]
 [53 65 80 84]]
[[58 74 53 89]
 [73 65 98 60]
 [80 84 52 84]]


In [91]:
x

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84]])

In [92]:
x.ravel()
x.flatten()

array([58, 74, 53, 89, 73, 65, 98, 60, 80, 84, 52, 84])

In [107]:
# fancy indexing
[0,1]
new_list = []
for i in [0,2,3]:
    new_list.append(list(np.ravel(x))[i])
# fancy indexing
np.ravel(x)[[0,2,3]]

array([58, 53, 89])

In [108]:
x[:2,:2] #앞이 행, 뒤가 열

array([[58, 74],
       [89, 73]])

In [109]:
!pip install pandas

                                              0.0/11.0 MB ? eta -:--:--
                                              0.2/11.0 MB 6.9 MB/s eta 0:00:02
     -                                        0.5/11.0 MB 6.4 MB/s eta 0:00:02
     --                                       0.8/11.0 MB 6.3 MB/s eta 0:00:02
     ----                                     1.1/11.0 MB 6.5 MB/s eta 0:00:02
     -----                                    1.5/11.0 MB 6.6 MB/s eta 0:00:02
     ------                                   1.8/11.0 MB 6.8 MB/s eta 0:00:02
     -------                                  2.1/11.0 MB 6.8 MB/s eta 0:00:02
     ---------                                2.5/11.0 MB 6.9 MB/s eta 0:00:02
     ----------                               2.8/11.0 MB 6.9 MB/s eta 0:00:02
     -----------                              3.1/11.0 MB 6.9 MB/s eta 0:00:02
     ------------                             3.5/11.0 MB 6.9 MB/s eta 0:00:02
     -------------                            3.8/11.0 MB 6


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [110]:
import pandas as pd

In [114]:
x

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84]])

In [112]:
pd.DataFrame(x).iloc[[1,3],[0,1]]

0   1
1  89  73
3  84  52

In [113]:
x[[1,3],[0,1]]

array([89, 52])

In [117]:
x[[1,3],:][:,[0,1]]

array([[89, 73],
       [84, 52]])