In [2]:
# (),{},[] 개념정리
import numpy as np
import pandas as pd

array([7, 7, 5, 6, 8, 6, 7])

In [ ]:
# numpy

In [9]:
# fancy indexing
# 1차원
x = np.random.randint(5,10,7)
x

array([8])

In [ ]:
x[[0,2,3]]
x[x >= 8]

In [28]:
# 2차원
x = np.random.randint(3,10,size=(4,2))
x

array([[8, 5],
       [7, 3],
       [8, 6],
       [5, 4]])

In [29]:
# 축 계산
x[2,1]

6

In [30]:
x[[2,3],:]

array([[8, 6],
       [5, 4]])

In [ ]:
# pandas

In [32]:
x = np.random.randint(3,10,size=(4,3))
x = pd.DataFrame(x)
x

0  1  2
0  6  3  7
1  9  7  8
2  6  6  8
3  5  9  7

In [33]:
# 1차원
#loc과 iloc을 안쓸경우 Column으로 인식
x[0] # [ ] = Series 형식
x[[0,1]] # [ [ ] ] = DataFrame 형식

0  1
0  6  3
1  9  7
2  6  6
3  5  9

In [36]:
x.columns = ['a','a b','c']

In [37]:
x[x>5]

a  a b  c
0  6.0  NaN  7
1  9.0  7.0  8
2  6.0  6.0  8
3  NaN  9.0  7

In [38]:
x.a
x['a b'] # x.a b(불가능) 공백이 포함되어있으면 .으로 가져올 수 없음

0    3
1    7
2    6
3    9
Name: a b, dtype: int32

In [39]:
x.columns = x.columns.str.replace(" ","") # 공백을 없애주는게 좋음

In [41]:
# df.속성 : Series 형식
# .컬럼명
# .columns
# .index
# .shape

# df.메서드
# .loc[ , ] : 
# .iloc[ , ] : 1.index(인덱스명이 아닌 위치 그대로), 2.slice, 3.boolean

In [47]:
x.loc[[2,3],['ab','c']]

ab  c
2   6  8
3   9  7

In [53]:
x.iloc[2:4,1:4]

ab  c
2   6  8
3   9  7