In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [7]:
np.NINF

-inf

In [13]:
np.all([1,2,3,0]) # aggregated 전부가 True여야 True

False

In [14]:
np.any([0,2,3]) # 하나라도 True라면 True

True

In [25]:
arr = np.array([1,2,3,4])
arr.ndim
arr.shape
np.append(arr,10)
arr

array([1, 2, 3, 4])

In [22]:
arr2 = [1,2,3,4]
arr2.append(10)
arr2

In [27]:
n_range = np.arange(1,11)
r = range(1,11)

In [30]:
[i + 5 for i in r]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [35]:
m1 = np.arange(1,21).reshape(4,5)

In [62]:
import pandas as pd
np.random.seed(100)
df = pd.DataFrame(np.random.randint(1,20,size=(10000000,5)))

In [59]:
def xx(x):
    s = 0
    for i in x:
        if i % 2 == 0:
            s += 1
    return s

In [63]:
a = df.apply(xx,1)

In [68]:
x = np.array([2,1,2,1,2,2,2])
np.where(x==1,True,False)

array([False,  True, False,  True, False, False, False])

In [69]:
def xxx(x):
    return np.sum(np.where(x%2==0,1,0))

In [70]:
b = df.apply(xxx,1)

KeyboardInterrupt: 

In [71]:
df.apply(lambda x: np.sum(np.where(x%2==0,1,0)),1)

KeyboardInterrupt: 

In [72]:
np.apply_along_axis(xxx,1,df.values)

array([3, 0, 2, ..., 3, 1, 3])

In [77]:
import math
math.sin(np.pi/2)
np.sin(np.pi/2)
np.e

2.718281828459045

In [83]:
arr = np.array([4,2,3])
np.argmax(arr) # 중요 2
np.argmin(arr) # 중요 2
np.argsort(arr) # 중요 1
np.min(arr) # 중요 3
np.max(arr) # 중요 3
np.sort(arr) # 중요 4

array([2, 3, 4])

In [90]:
round(7/96,2)
np.around([7/96,5/13],2)

array([0.07, 0.38])

In [94]:
m1 = np.random.randint(1,10,size=(2,3))
m2 = np.random.randint(1,10,size=(3,2))

In [97]:
np.dot(m1,m2)

array([[ 24,   5],
       [126,  23]])

In [98]:
m3 = np.asmatrix(m1)
m4 = np.asmatrix(m2)
m3*m4

matrix([[ 24,   5],
        [126,  23]])

In [103]:
np.byte(m3)

matrix([[2, 1, 1],
        [7, 4, 8]], dtype=int8)

In [104]:
import sys
sys.getsizeof([1,2,3])

88

In [109]:
r = range(1,10000000)

In [108]:
sys.getsizeof(r)

48

In [110]:
r1 = list(range(1,10000000))

In [112]:
sys.getsizeof(r1)

80000056